version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "uv"
    directory: "/server"
    schedule:
      interval: "weekly"

  - package-ecosystem: "uv"
    directory: "/cli"
    schedule:
      interval: "weekly"

  - package-ecosystem: "uv"
    directory: "/lib"
    schedule:
      interval: "weekly"
